[tool.poetry]
name = "genome"
version = "0.1.0"
description = ""
authors = ["Andrew Grosser <dioptre@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pysam = "^0.22.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
